Repository StevensSEC/pokemonbattlelib, pull requests merged in 2021-02, with the labels that each got.

#14 add RNG interface, add LCRNG
  rng.go
  rng_test.go
Labels: enhancement

#13 Pokemon Battle Engine
  agent.go
  agent_test.go
  battle.go
  battle_test.go
Labels: enhancement

#17 Added move type
  move.go
  move_test.go
Labels: enhancement

#28 add link to documentation in README
  README.md
Labels: meta/documentation, meta/maintenance

#26 Complete system to allow agents to make turns
  agent.go
  agent_test.go
  battle.go
  battle_test.go
  util.go
Labels: enhancement, refactor

#37 Enforce code formatting and updated codegen in CI tests
  .github/workflows/test.yml
  ability.go
  data/gen.go
  elemental_type.go
  exp_group.go
  gender.go
  gender_test.go
  move.go
  move_test.go
  nature.go
  pokedex_GEN.go
  pokemon_test.go
Labels: meta/workflow

#30 Add code generation for moves
  data/gen.go
  move.go
  move_test.go
  pokedex_GEN.go
Labels: enhancement

#40 battle docs and helpers
  battle.go
Labels: meta/documentation, refactor

#39 Code generation for pokemon adds all fields
  data/gen.go
  pokedex_GEN.go
  pokemon.go
Labels: enhancement

#52 refactor out the necessity of LinkAgentParty, fixes #44
  battle.go
  battle_test.go
Labels: refactor

#55 add vscode debug launcher
  .vscode/launch.json
Labels: meta/maintenance

#56 add GetMove, add moves to pokemon in test cases
  battle_test.go
  pokedex.go
Labels: enhancement, testing

#59 Add playground for trying the library out and manual testing
  .vscode/launch.json
  playground/go.mod
  playground/playground.go
Labels: meta/maintenance

#63 add coverage.out to gitignore
  .gitignore
Labels: meta/maintenance

#62 Table-ize some tests
  gender.go
  gender_test.go
  move_test.go
  pokemon.go
  pokemon_test.go
Labels: refactor

#64 add a vscode task to run the tests, collect test coverage and open it for viewing
  .vscode/tasks.json
Labels: enhancement, meta/maintenance

#67 fix typo in fight turn implementation
  battle.go
Labels: bug

#57 Battle rework v3
  .vscode/tasks.json
  agent.go
  battle.go
  battle_test.go
  items.go
  move.go
  move_test.go
  party.go
  pokedex.go
  pokedex_test.go
  pokemon.go
  pokemon_test.go
  util.go
Labels: refactor

#71 redo playground changes that somehow got reverted, and added utils for playground
  playground/.gitignore
  playground/README.md
  playground/playground.go.template
Labels: meta/documentation, meta/maintenance

#73 fix get opponents
  battle.go
  battle_test.go
Labels: bug

#69 Battle Log - Solution B
  battle.go
  battle_test.go
Labels: enhancement

#79 bring back pokedex.go with codegen comment, fixes #77
  pokedex.go
Labels: bug

#108 move helper types/constants to types.go
  ability.go
  exp_group.go
  gender.go
  gender_test.go
  nature.go
  pokemon.go
  types.go
  types_test.go
Labels: refactor

#110 Refactor Transaction queue processing
  battle.go
Labels: refactor

#120 fix status condition check for non volatile statuses, adjust bits for status condition constants fixes #118
  types.go
  types_test.go
Labels: bug

#119 add status condition stringer
  types.go
  types_test.go
Labels: enhancement

#121 refactor transactions to use `target` instead
  battle.go
  transactions.go
Labels: refactor

#129 Added with moves method
  pokemon.go
Labels: enhancement

#117 Add Gomega and Ginkgo tests
  .vscode/launch.json
  .vscode/tasks.json
  README.md
  battle_test.go
  go.mod
  go.sum
  items_test.go
  pokemon.go
  pokemon_test.go
  pokemonbattlelib_suite_test.go
  rng_test.go
Labels: refactor, testing

#134 no more zombie turns
  battle.go
  battle_test.go
Labels: bug

#122 add post-turn status effects: burn, poison
  battle.go
  battle_test.go
  transactions.go
Labels: enhancement

#131 fix #127
  battle.go
Labels: bug

#124 add private rng field to battle
  battle.go
  battle_test.go
Labels: enhancement

#125 add rcAgent, closes #75
  battle_test.go
Labels: enhancement, testing

#128 add a benchmark
  .vscode/launch.json
  benchmark_test.go
Labels: testing

#126 add ItemFlags, and update codegen
  data/gen.go
  items.go
  pokedex_GEN.go
Labels: enhancement

#139 fix vscode test launcher
  .vscode/launch.json
Labels: meta/maintenance

#138 add move priority to sorting
  battle.go
  battle_test.go
Labels: enhancement

#155 Golangci-lint
  .golangci.yaml
Labels: meta/maintenance

#151 add Paralysis, Freeze, Sleep status checks
  battle.go
  battle_test.go
  transactions.go
Labels: enhancement

#161 add CureStatusTransaction
  battle.go
  battle_test.go
  transactions.go
Labels: enhancement

#165 Accuracy
  battle.go
  battle_test.go
  transactions.go
Labels: enhancement

#162 mutate transactions
  battle.go
  transactions.go
Labels: refactor

#172 GetMove returns *Move
  battle_test.go
  move.go
  pokemon_test.go
Labels: refactor
