Repository StevensSEC/pokemonbattlelib, pull requests merged in 2021-03, with the labels that each got.

#164 add custom gomega matchers for transactions
  battle_test.go
  util_test.go
Labels: enhancement, testing

#175 Improve docs
  battle.go
  items.go
  pokemon.go
  rng.go
  transactions.go
  types.go
Labels: enhancement, meta/documentation

#143 Weather / Weather Modifiers
  battle.go
  battle_test.go
  transactions.go
  types.go
  util_test.go
Labels: enhancement

#178 Add an optional HTTP API
  .vscode/launch.json
  go.mod
  go.sum
  http/.gitignore
  http/README.md
  http/agent.go
  http/api.go
  http/main.go
  http/util.go
  pokemon.go
Labels: enhancement

#205 Refactor how Nature works
  data/gen.go
  data/natures.csv
  pokedex_GEN.go
  pokemon.go
  pokemon_test.go
  types.go
  types_test.go
  util_test.go
Labels: enhancement, refactor

#113 Implement EV Transactions
  battle_test.go
  transactions.go
Labels: enhancement

#208 Small refactors to existing tests
  battle_test.go
  pokemon.go
  pokemon_test.go
Labels: refactor, testing

#207 refactor: elemental type tests
  types_test.go
Labels: refactor, testing

#188 add in-a-pinch berries
  battle.go
  battle_test.go
  items.go
  transactions.go
Labels: enhancement

#231 item refactor
  battle.go
  battle_test.go
  data/gen.go
  items.go
  items_test.go
  pokedex_GEN.go
  pokemon.go
  transactions.go
  util_test.go
Labels: refactor

#257 add content type headers
  http/api.go
Labels: bug

#256 move refactor
  .github/workflows/test.yml
  battle.go
  battle_test.go
  benchmark_test.go
  data/gen.go
  go.mod
  go.sum
  http/api.go
  move.go
  move_getters_GEN.go
  move_test.go
  pokedex_GEN.go
  scripts/gen_getters.go
  transactions.go
Labels: component/pokedex, refactor

#258 simulate refactor
  battle.go
  battle_test.go
  calc.go
Labels: component/battle, refactor

#263 add team/party validation
  battle.go
  battle_test.go
Labels: component/battle, feature

#264 refactor item getters to be auto generated
  item_getters_GEN.go
  items.go
Labels: component/pokedex, refactor

#260 add getter for a pokemon's type to allow overriding
  battle.go
  calc.go
  pokemon.go
Labels: component/battle, feature

#261 Ability refactor and codegen
  battle_test.go
  calc.go
  data/gen.go
  pokedex_GEN.go
  pokemon.go
  pokemon_test.go
  types.go
  types_test.go
Labels: component/pokedex, feature, refactor

#265 fail transaction
  battle.go
  battle_test.go
  transactions.go
  types.go
  util_test.go
Labels: component/battle, refactor

#262 add missing item flags, fixes #204
  data/gen.go
  pokedex_GEN.go
Labels: bug, component/pokedex

#270 `PokemonData` refactor
  data/gen.go
  pokedex_GEN.go
  pokemon.go
  pokemon_test.go
Labels: component/pokedex, refactor

#269 party validation
  battle.go
  battle_test.go
  party.go
  party_test.go
  pokemon.go
  pokemon_test.go
Labels: component/pokedex, feature

#276 improve ci logs
  .github/workflows/test.yml
Labels: meta/workflow

#277 Evasion
  battle.go
  battle_test.go
  pokemon.go
  types.go
Labels: component/battle, feature

#278 Increase test isolation
  battle_test.go
  util_test.go
Labels: refactor, testing

#284 Add type matchups to damage calculation
  battle_test.go
  calc.go
  types.go
Labels: component/battle, feature, refactor

#295 Refactor target to have ground truth pointer
  agent_test.go
  battle.go
  battle_test.go
  transactions.go
  util_test.go
Labels: bug, component/battle, refactor
